# Generated by Django 5.2.6 on 2026-10-08 07:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedJobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(db_index=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('FAILED', 'Failed'), ('RESOLVED', 'Resolved')], db_index=True, default='FAILED', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('exception_type', models.CharField(max_length=500)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('task_args', models.JSONField(blank=True, default=list)),
                ('task_kwargs', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'failed_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_name', 'status'], name='failed_job_task_status_idx'), models.Index(fields=['tenant_id', 'status'], name='failed_job_tenant_status_idx'), models.Index(fields=['created_at'], name='failed_job_created_idx')],
            },
        ),
    ]
