DEFAULT_PERMISSIONS = [
    {
        "code": "tenant.read",
        "name": "Read Tenant",
        "description": "View tenant information.",
    },
    {
        "code": "tenant.update",
        "name": "Update Tenant",
        "description": "Update tenant information.",
    },
    {
        "code": "users.read",
        "name": "Read Users",
        "description": "View tenant users.",
    },
    {
        "code": "users.create",
        "name": "Create Users",
        "description": "Create or invite tenant users.",
    },
    {
        "code": "users.update",
        "name": "Update Users",
        "description": "Update tenant user information.",
    },
    {
        "code": "users.delete",
        "name": "Delete Users",
        "description": "Remove users from a tenant.",
    },
    {
        "code": "projects.read",
        "name": "Read Projects",
        "description": "View tenant projects.",
    },
    {
        "code": "projects.create",
        "name": "Create Projects",
        "description": "Create tenant projects.",
    },
    {
        "code": "projects.update",
        "name": "Update Projects",
        "description": "Update tenant projects.",
    },
    {
        "code": "projects.delete",
        "name": "Delete Projects",
        "description": "Delete tenant projects.",
    },
    {
        "code": "tasks.read",
        "name": "Read Tasks",
        "description": "View tenant tasks.",
    },
    {
        "code": "tasks.create",
        "name": "Create Tasks",
        "description": "Create tenant tasks.",
    },
    {
        "code": "tasks.update",
        "name": "Update Tasks",
        "description": "Update tenant tasks.",
    },
    {
        "code": "tasks.delete",
        "name": "Delete Tasks",
        "description": "Delete tenant tasks.",
    },
    {
        "code": "billing.read",
        "name": "Read Billing",
        "description": "View tenant billing information.",
    },
    {
        "code": "billing.manage",
        "name": "Manage Billing",
        "description": "Manage tenant billing.",
    },
]

DEFAULT_TENANT_ROLES = {
    "OWNER": [
        "tenant.read",
        "tenant.update",
        "users.read",
        "users.create",
        "users.update",
        "users.delete",
        "projects.read",
        "projects.create",
        "projects.update",
        "projects.delete",
        "tasks.read",
        "tasks.create",
        "tasks.update",
        "tasks.delete",
        "billing.read",
        "billing.manage",
    ],
    "ADMIN": [
        "tenant.read",
        "tenant.update",
        "users.read",
        "users.create",
        "users.update",
        "users.delete",
        "projects.read",
        "projects.create",
        "projects.update",
        "projects.delete",
        "tasks.read",
        "tasks.create",
        "tasks.update",
        "tasks.delete",
        "billing.read",
    ],
    "MANAGER": [
        "tenant.read",
        "users.read",
        "projects.read",
        "projects.create",
        "projects.update",
        "tasks.read",
        "tasks.create",
        "tasks.update",
    ],
    "MEMBER": [
        "tenant.read",
        "projects.read",
        "tasks.read",
        "tasks.create",
        "tasks.update",
    ],
    "VIEWER": [
        "tenant.read",
        "projects.read",
        "tasks.read",
    ],
}