DEFAULT_PERMISSIONS = [
    {
        "code": "tenant.read",
        "name": "Read Tenant",
        "description": "View tenant information.",
    },
    {
        "code": "tenant.update",
        "name": "Update Tenant",
        "description": "Update tenant information.",
    },
    {
        "code": "users.read",
        "name": "Read Users",
        "description": "View tenant users.",
    },
    {
        "code": "users.create",
        "name": "Create Users",
        "description": "Create or invite tenant users.",
    },
    {
        "code": "users.update",
        "name": "Update Users",
        "description": "Update tenant user information.",
    },
    {
        "code": "users.delete",
        "name": "Delete Users",
        "description": "Remove users from a tenant.",
    },
    {
        "code": "projects.read",
        "name": "Read Projects",
        "description": "View tenant projects.",
    },
    {
        "code": "projects.create",
        "name": "Create Projects",
        "description": "Create tenant projects.",
    },
    {
        "code": "projects.update",
        "name": "Update Projects",
        "description": "Update tenant projects.",
    },
    {
        "code": "projects.delete",
        "name": "Delete Projects",
        "description": "Delete tenant projects.",
    },
    {
        "code": "tasks.read",
        "name": "Read Tasks",
        "description": "View tenant tasks.",
    },
    {
        "code": "tasks.create",
        "name": "Create Tasks",
        "description": "Create tenant tasks.",
    },
    {
        "code": "tasks.update",
        "name": "Update Tasks",
        "description": "Update tenant tasks.",
    },
    {
        "code": "tasks.delete",
        "name": "Delete Tasks",
        "description": "Delete tenant tasks.",
    },
    {
        "code": "teams.read",
        "name": "Read Teams",
        "description": "View tenant teams.",
    },
    {
        "code": "teams.create",
        "name": "Create Teams",
        "description": "Create tenant teams.",
    },
    {
        "code": "teams.update",
        "name": "Update Teams",
        "description": "Update tenant teams.",
    },
    {
        "code": "teams.delete",
        "name": "Delete Teams",
        "description": "Delete tenant teams.",
    },
    {
        "code": "comments.read",
        "name": "Read Comments",
        "description": "View task comments.",
    },
    {
        "code": "comments.create",
        "name": "Create Comments",
        "description": "Create task comments.",
    },
    {
        "code": "comments.update",
        "name": "Update Comments",
        "description": "Update task comments.",
    },
    {
        "code": "comments.delete",
        "name": "Delete Comments",
        "description": "Delete task comments.",
    },
    {
        "code": "attachments.read",
        "name": "Read Attachments",
        "description": "View task attachments.",
    },
    {
        "code": "attachments.create",
        "name": "Create Attachments",
        "description": "Create task attachments.",
    },
    {
        "code": "attachments.delete",
        "name": "Delete Attachments",
        "description": "Delete task attachments.",
    },
    {
        "code": "tags.read",
        "name": "Read Tags",
        "description": "View tenant tags.",
    },
    {
        "code": "tags.create",
        "name": "Create Tags",
        "description": "Create tenant tags.",
    },
    {
        "code": "tags.update",
        "name": "Update Tags",
        "description": "Update tenant tags.",
    },
    {
        "code": "tags.delete",
        "name": "Delete Tags",
        "description": "Delete tenant tags.",
    },
    {
        "code": "tags.assign",
        "name": "Assign Tags",
        "description": "Assign tags to tasks.",
    },
    {
        "code": "billing.read",
        "name": "Read Billing",
        "description": "View tenant billing information.",
    },
    {
        "code": "billing.manage",
        "name": "Manage Billing",
        "description": "Manage tenant billing.",
    },
    {
        "code": "roles.read",
        "name": "Read Roles",
        "description": "View tenant roles.",
    },
    {
        "code": "roles.create",
        "name": "Create Roles",
        "description": "Create tenant roles.",
    },
    {
        "code": "roles.update",
        "name": "Update Roles",
        "description": "Update tenant roles.",
    },
    {
        "code": "roles.delete",
        "name": "Delete Roles",
        "description": "Delete tenant roles.",
    },
    {
        "code": "roles.assign",
        "name": "Assign Roles",
        "description": "Assign roles to tenant memberships.",
    },
]


DEFAULT_TENANT_ROLES = {
    "OWNER": [
        "tenant.read",
        "tenant.update",
        "users.read",
        "users.create",
        "users.update",
        "users.delete",
        "projects.read",
        "projects.create",
        "projects.update",
        "projects.delete",
        "tasks.read",
        "tasks.create",
        "tasks.update",
        "tasks.delete",
        "teams.read",
        "teams.create",
        "teams.update",
        "teams.delete",
        "comments.read",
        "comments.create",
        "comments.update",
        "comments.delete",
        "attachments.read",
        "attachments.create",
        "attachments.delete",
        "tags.read",
        "tags.create",
        "tags.update",
        "tags.delete",
        "tags.assign",
        "billing.read",
        "billing.manage",
        "roles.read",
        "roles.create",
        "roles.update",
        "roles.delete",
        "roles.assign",
    ],
    "ADMIN": [
        "tenant.read",
        "tenant.update",
        "users.read",
        "users.create",
        "users.update",
        "users.delete",
        "projects.read",
        "projects.create",
        "projects.update",
        "projects.delete",
        "tasks.read",
        "tasks.create",
        "tasks.update",
        "tasks.delete",
        "teams.read",
        "teams.create",
        "teams.update",
        "teams.delete",
        "comments.read",
        "comments.create",
        "comments.update",
        "comments.delete",
        "attachments.read",
        "attachments.create",
        "attachments.delete",
        "tags.read",
        "tags.create",
        "tags.update",
        "tags.delete",
        "tags.assign",
        "billing.read",
        "roles.read",
        "roles.create",
        "roles.update",
        "roles.delete",
        "roles.assign",
    ],
    "MANAGER": [
        "tenant.read",
        "users.read",
        "projects.read",
        "projects.create",
        "projects.update",
        "tasks.read",
        "tasks.create",
        "tasks.update",
        "teams.read",
        "teams.create",
        "teams.update",
        "comments.read",
        "comments.create",
        "comments.update",
        "attachments.read",
        "attachments.create",
        "attachments.delete",
        "tags.read",
        "tags.create",
        "tags.update",
        "tags.delete",
        "tags.assign",
    ],
    "MEMBER": [
        "tenant.read",
        "projects.read",
        "tasks.read",
        "tasks.create",
        "tasks.update",
        "teams.read",
        "comments.read",
        "comments.create",
        "attachments.read",
        "attachments.create",
        "tags.read",
        "tags.assign",
    ],
    "VIEWER": [
        "tenant.read",
        "projects.read",
        "tasks.read",
        "teams.read",
        "comments.read",
        "attachments.read",
        "tags.read",
    ],
}


PLATFORM_ROLE_DEFINITIONS = {
    "SUPER_ADMIN": {
        "name": "Super Admin",
        "description": (
            "Full platform-level administrative access."
        ),
        "permissions": [
            "tenant.read",
            "tenant.update",
            "users.read",
            "users.create",
            "users.update",
            "users.delete",
            "projects.read",
            "projects.create",
            "projects.update",
            "projects.delete",
            "tasks.read",
            "tasks.create",
            "tasks.update",
            "tasks.delete",
            "teams.read",
            "teams.create",
            "teams.update",
            "teams.delete",
            "comments.read",
            "comments.create",
            "comments.update",
            "comments.delete",
            "attachments.read",
            "attachments.create",
            "attachments.delete",
            "tags.read",
            "tags.create",
            "tags.update",
            "tags.delete",
            "tags.assign",
            "billing.read",
            "billing.manage",
            "roles.read",
            "roles.create",
            "roles.update",
            "roles.delete",
            "roles.assign",
        ],
    },
    "SUPPORT": {
        "name": "Support",
        "description": (
            "Platform support access for operational assistance."
        ),
        "permissions": [
            "tenant.read",
            "users.read",
            "projects.read",
            "tasks.read",
            "teams.read",
            "comments.read",
            "attachments.read",
            "tags.read",
            "billing.read",
        ],
    },
    "OPERATIONS": {
        "name": "Operations",
        "description": (
            "Platform operations access."
        ),
        "permissions": [
            "tenant.read",
            "tenant.update",
            "users.read",
            "projects.read",
            "tasks.read",
            "teams.read",
            "comments.read",
            "attachments.read",
            "tags.read",
            "billing.read",
        ],
    },
}