from django.urls import path
from .views import (
    TenantCreateView,
    TenantListView,
    CurrentTenantView,
    TenantActivateView,
    TenantDeactivateView,
    TenantSuspendView,
    MembershipRoleView,
    RoleObjectPermissionView,
    TenantRoleDetailView,
    TenantRoleListCreateView,
    UserObjectPermissionView,
)

urlpatterns = [
    path(
        "", 
        TenantCreateView.as_view(), 
        name="tenant-create"
    ),
    path(
        "list/",
        TenantListView.as_view(),
        name="tenant-list",
    ),
    path(
        "<uuid:tenant_id>/",
        CurrentTenantView.as_view(),
        name="current-tenant",
    ),
    path(
        "<uuid:tenant_id>/suspend/",
        TenantSuspendView.as_view(),
        name="tenant-suspend",
    ),
    path(
        "<uuid:tenant_id>/activate/",
        TenantActivateView.as_view(),
        name="tenant-activate",
    ),
    path(
        "<uuid:tenant_id>/deactivate/",
        TenantDeactivateView.as_view(),
        name="tenant-deactivate",
    ),
    path(
        "roles/",
        TenantRoleListCreateView.as_view(),
        name="rbac-role-list-create",
    ),
    path(
        "roles/<uuid:role_id>/",
        TenantRoleDetailView.as_view(),
        name="rbac-role-detail",
    ),
    path(
        "memberships/<uuid:membership_id>/role/",
        MembershipRoleView.as_view(),
        name="rbac-membership-role",
    ),
    path(
        "object-permissions/users/",
        UserObjectPermissionView.as_view(),
        name="rbac-user-object-permission",
    ),
    path(
        "object-permissions/roles/",
        RoleObjectPermissionView.as_view(),
        name="rbac-role-object-permission",
    ),
]