# Generated by Django 6.0.8 on 2026-10-02 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant_id', 'name'], name='tag_tenant_name_idx'), models.Index(fields=['tenant_id', 'created_by'], name='tag_tenant_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'name'), name='tag_tenant_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('task_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='tags.tag')),
            ],
            options={
                'db_table': 'task_tags',
                'indexes': [models.Index(fields=['tenant_id', 'task_id'], name='tasktag_tenant_task_idx'), models.Index(fields=['tenant_id', 'tag'], name='tasktag_tenant_tag_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'task_id', 'tag'), name='task_tag_unique')],
            },
        ),
    ]
