# Generated by Django 6.0.8 on 2026-09-15 12:23

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id'], name='tenants_ten_id_e282b7_idx'), models.Index(fields=['slug'], name='tenants_ten_slug_63daca_idx'), models.Index(fields=['status'], name='tenants_ten_status_e7eaee_idx'), models.Index(fields=['created_at'], name='tenants_ten_created_99c6ff_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='tenant_slug_ci_unique')],
            },
        ),
    ]
