# Generated by Django 6.0.8 on 2026-09-15 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('suspended', 'Suspended'), ('removed', 'Removed')], db_index=True, default='active', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='membership_tenant_status_idx'), models.Index(fields=['user_id', 'status'], name='membership_user_status_idx'), models.Index(fields=['joined_at', 'created_at'], name='membership_joined_at_created_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user_id'), name='tenant_membership_tenant_user_unique')],
            },
        ),
    ]
