# Generated by Django 6.0.8 on 2026-09-19 16:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('actor_user_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(choices=[('tenant.created', 'Tenant Created'), ('tenant.updated', 'Tenant Updated'), ('tenant.suspended', 'Tenant Suspended'), ('tenant.activated', 'Tenant Activated'), ('tenant.deactivated', 'Tenant Deactivated')], db_index=True, max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='tenantmembership',
            new_name='membership_jd_at_cd_at_idx',
            old_name='membership_joined_at_created_at_idx',
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['tenant_id', 'created_at'], name='audit_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['tenant_id', 'event_type'], name='audit_tenant_event_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor_user_id', 'created_at'], name='audit_actor_created_idx'),
        ),
    ]
