# Generated by Django 6.0.8 on 2026-09-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_permission_role_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantmembership',
            new_name='membership_tenant_status_idx',
            old_name='membership_tenant_status_role_idx',
        ),
    ]
