# Generated by Django 6.0.8 on 2026-09-25 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_rename_membership_tenant_status_role_idx_membership_tenant_status_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('user', 'User'), ('role', 'Role')], max_length=20)),
                ('subject_id', models.UUIDField()),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_permissions', to='tenants.permission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_permissions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['resource_type', 'resource_id', 'permission__code'],
                'indexes': [models.Index(fields=['tenant', 'resource_type', 'resource_id'], name='obj_perm_resource_idx'), models.Index(fields=['tenant', 'subject_type', 'subject_id'], name='obj_perm_subject_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'subject_type', 'subject_id', 'resource_type', 'resource_id', 'permission'), name='object_permission_unique')],
            },
        ),
    ]
