# Generated by Django 6.0.8 on 2026-09-25 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_objectpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_assignments', to='tenants.role')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user_id', 'role'], name='platform_user_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'role'), name='platform_user_role_unique')],
            },
        ),
    ]
