# Generated by Django 5.2.6 on 2026-10-06 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(choices=[('USER_INVITED', 'User Invited'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('PASSWORD_RESET', 'Password Reset'), ('SUBSCRIPTION_CREATED', 'Subscription Created'), ('PAYMENT_FAILED', 'Payment Failed'), ('REPORT_READY', 'Report Ready')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['tenant_id', 'user_id'], name='notificatio_tenant__c12e41_idx'), models.Index(fields=['tenant_id', 'status'], name='notificatio_tenant__165236_idx'), models.Index(fields=['tenant_id', 'event_type'], name='notificatio_tenant__b25ec4_idx'), models.Index(fields=['tenant_id', 'created_at'], name='notificatio_tenant__f87df4_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(choices=[('USER_INVITED', 'User Invited'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('PASSWORD_RESET', 'Password Reset'), ('SUBSCRIPTION_CREATED', 'Subscription Created'), ('PAYMENT_FAILED', 'Payment Failed'), ('REPORT_READY', 'Report Ready')], max_length=100)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
                'indexes': [models.Index(fields=['tenant_id', 'user_id'], name='notificatio_tenant__52fe84_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'user_id', 'event_type'), name='unique_notification_preference')],
            },
        ),
    ]
