# Generated by Django 5.2.6 on 2026-10-07 07:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('requested_by', models.UUIDField(db_index=True)),
                ('export_type', models.CharField(choices=[('PROJECTS', 'Projects'), ('USERS', 'Users'), ('TASKS', 'Tasks'), ('AUDIT_LOGS', 'Audit Logs')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exports_export',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='export_tenant_status_idx'), models.Index(fields=['tenant_id', 'export_type'], name='export_tenant_type_idx'), models.Index(fields=['tenant_id', 'created_at'], name='export_tenant_created_idx')],
            },
        ),
    ]
