# Generated by Django 6.0.8 on 2026-10-02 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('task_id', models.UUIDField(db_index=True)),
                ('content', models.TextField()),
                ('created_by', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'task_id'], name='comment_tenant_task_idx'), models.Index(fields=['tenant_id', 'created_by'], name='comment_tenant_user_idx'), models.Index(fields=['tenant_id', 'created_at'], name='comment_tenant_created_idx')],
            },
        ),
    ]
