# Generated by Django 6.0.8 on 2026-10-01 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='team_tenant_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'name'), name='team_tenant_name_unique')],
            },
        ),
    ]
